// Auth Types

export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const ACCESS_TYPE = 'ACCESS_TYPE';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const UPDATE_USER = 'UPDATE_USER';

// Cases Type

export const FETCH_CASES_LOADING = 'FETCH_CASES_LOADING';
export const FETCH_CASE_SUCCESS = 'FETCH_CASE_SUCCESS';
export const FETCH_CASES_SUCCESS = 'FETCH_CASES_SUCCESS';
export const FETCH_CASES_ERROR = 'FETCH_CASES_ERROR';
export const UPDATE_CASE_PAGE= 'UPDATE_CASE_PAGE';